package com.macro.mall.mapper;

import com.macro.mall.model.DspBranchWarehouse;

public interface DspBranchWarehouseMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsp_branch_warehouse
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsp_branch_warehouse
     *
     * @mbggenerated
     */
    int insert(DspBranchWarehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsp_branch_warehouse
     *
     * @mbggenerated
     */
    int insertSelective(DspBranchWarehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsp_branch_warehouse
     *
     * @mbggenerated
     */
    DspBranchWarehouse selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsp_branch_warehouse
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DspBranchWarehouse record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsp_branch_warehouse
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DspBranchWarehouse record);
}