package com.macro.mall.mapper;

import com.macro.mall.model.DspBranchWarehouseRuleAttr;

public interface DspBranchWarehouseRuleAttrMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsp_branch_warehouse_rule_attr
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsp_branch_warehouse_rule_attr
     *
     * @mbggenerated
     */
    int insert(DspBranchWarehouseRuleAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsp_branch_warehouse_rule_attr
     *
     * @mbggenerated
     */
    int insertSelective(DspBranchWarehouseRuleAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsp_branch_warehouse_rule_attr
     *
     * @mbggenerated
     */
    DspBranchWarehouseRuleAttr selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsp_branch_warehouse_rule_attr
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DspBranchWarehouseRuleAttr record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsp_branch_warehouse_rule_attr
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DspBranchWarehouseRuleAttr record);
}