package com.macro.mall.mapper;

import com.macro.mall.model.DspBranchWarehouseRule;

public interface DspBranchWarehouseRuleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsp_branch_warehouse_rule
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long ruleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsp_branch_warehouse_rule
     *
     * @mbggenerated
     */
    int insert(DspBranchWarehouseRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsp_branch_warehouse_rule
     *
     * @mbggenerated
     */
    int insertSelective(DspBranchWarehouseRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsp_branch_warehouse_rule
     *
     * @mbggenerated
     */
    DspBranchWarehouseRule selectByPrimaryKey(Long ruleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsp_branch_warehouse_rule
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(DspBranchWarehouseRule record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsp_branch_warehouse_rule
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(DspBranchWarehouseRule record);
}