package com.macro.mall.model;

import java.io.Serializable;
import java.util.Date;

public class DspBranchWarehouseRuleAttr implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsp_branch_warehouse_rule_attr.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsp_branch_warehouse_rule_attr.area_rule
     *
     * @mbggenerated
     */
    private String areaRule;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsp_branch_warehouse_rule_attr.attr_name
     *
     * @mbggenerated
     */
    private String attrName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsp_branch_warehouse_rule_attr.attr_value
     *
     * @mbggenerated
     */
    private String attrValue;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsp_branch_warehouse_rule_attr.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsp_branch_warehouse_rule_attr.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsp_branch_warehouse_rule_attr.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsp_branch_warehouse_rule_attr.update_user
     *
     * @mbggenerated
     */
    private String updateUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dsp_branch_warehouse_rule_attr
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsp_branch_warehouse_rule_attr.id
     *
     * @return the value of dsp_branch_warehouse_rule_attr.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsp_branch_warehouse_rule_attr.id
     *
     * @param id the value for dsp_branch_warehouse_rule_attr.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsp_branch_warehouse_rule_attr.area_rule
     *
     * @return the value of dsp_branch_warehouse_rule_attr.area_rule
     *
     * @mbggenerated
     */
    public String getAreaRule() {
        return areaRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsp_branch_warehouse_rule_attr.area_rule
     *
     * @param areaRule the value for dsp_branch_warehouse_rule_attr.area_rule
     *
     * @mbggenerated
     */
    public void setAreaRule(String areaRule) {
        this.areaRule = areaRule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsp_branch_warehouse_rule_attr.attr_name
     *
     * @return the value of dsp_branch_warehouse_rule_attr.attr_name
     *
     * @mbggenerated
     */
    public String getAttrName() {
        return attrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsp_branch_warehouse_rule_attr.attr_name
     *
     * @param attrName the value for dsp_branch_warehouse_rule_attr.attr_name
     *
     * @mbggenerated
     */
    public void setAttrName(String attrName) {
        this.attrName = attrName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsp_branch_warehouse_rule_attr.attr_value
     *
     * @return the value of dsp_branch_warehouse_rule_attr.attr_value
     *
     * @mbggenerated
     */
    public String getAttrValue() {
        return attrValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsp_branch_warehouse_rule_attr.attr_value
     *
     * @param attrValue the value for dsp_branch_warehouse_rule_attr.attr_value
     *
     * @mbggenerated
     */
    public void setAttrValue(String attrValue) {
        this.attrValue = attrValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsp_branch_warehouse_rule_attr.create_time
     *
     * @return the value of dsp_branch_warehouse_rule_attr.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsp_branch_warehouse_rule_attr.create_time
     *
     * @param createTime the value for dsp_branch_warehouse_rule_attr.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsp_branch_warehouse_rule_attr.create_user
     *
     * @return the value of dsp_branch_warehouse_rule_attr.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsp_branch_warehouse_rule_attr.create_user
     *
     * @param createUser the value for dsp_branch_warehouse_rule_attr.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsp_branch_warehouse_rule_attr.update_time
     *
     * @return the value of dsp_branch_warehouse_rule_attr.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsp_branch_warehouse_rule_attr.update_time
     *
     * @param updateTime the value for dsp_branch_warehouse_rule_attr.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsp_branch_warehouse_rule_attr.update_user
     *
     * @return the value of dsp_branch_warehouse_rule_attr.update_user
     *
     * @mbggenerated
     */
    public String getUpdateUser() {
        return updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsp_branch_warehouse_rule_attr.update_user
     *
     * @param updateUser the value for dsp_branch_warehouse_rule_attr.update_user
     *
     * @mbggenerated
     */
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsp_branch_warehouse_rule_attr
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", areaRule=").append(areaRule);
        sb.append(", attrName=").append(attrName);
        sb.append(", attrValue=").append(attrValue);
        sb.append(", createTime=").append(createTime);
        sb.append(", createUser=").append(createUser);
        sb.append(", updateTime=").append(updateTime);
        sb.append(", updateUser=").append(updateUser);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}