package com.macro.mall.model;

import java.io.Serializable;

public class DspBranchWarehouseRule implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsp_branch_warehouse_rule.rule_id
     *
     * @mbggenerated
     */
    private Long ruleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsp_branch_warehouse_rule.rule_name
     *
     * @mbggenerated
     */
    private String ruleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dsp_branch_warehouse_rule
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsp_branch_warehouse_rule.rule_id
     *
     * @return the value of dsp_branch_warehouse_rule.rule_id
     *
     * @mbggenerated
     */
    public Long getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsp_branch_warehouse_rule.rule_id
     *
     * @param ruleId the value for dsp_branch_warehouse_rule.rule_id
     *
     * @mbggenerated
     */
    public void setRuleId(Long ruleId) {
        this.ruleId = ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsp_branch_warehouse_rule.rule_name
     *
     * @return the value of dsp_branch_warehouse_rule.rule_name
     *
     * @mbggenerated
     */
    public String getRuleName() {
        return ruleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsp_branch_warehouse_rule.rule_name
     *
     * @param ruleName the value for dsp_branch_warehouse_rule.rule_name
     *
     * @mbggenerated
     */
    public void setRuleName(String ruleName) {
        this.ruleName = ruleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsp_branch_warehouse_rule
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", ruleId=").append(ruleId);
        sb.append(", ruleName=").append(ruleName);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}