package com.macro.mall.model;

import java.io.Serializable;
import java.util.Date;

public class DspBranchWarehouse implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsp_branch_warehouse.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsp_branch_warehouse.area_id
     *
     * @mbggenerated
     */
    private Integer areaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsp_branch_warehouse.area_name
     *
     * @mbggenerated
     */
    private String areaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsp_branch_warehouse.rule_id
     *
     * @mbggenerated
     */
    private String ruleId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsp_branch_warehouse.rule_name
     *
     * @mbggenerated
     */
    private String ruleName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsp_branch_warehouse.rule_rank
     *
     * @mbggenerated
     */
    private Integer ruleRank;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsp_branch_warehouse.create_date
     *
     * @mbggenerated
     */
    private Date createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsp_branch_warehouse.modify_date
     *
     * @mbggenerated
     */
    private Date modifyDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsp_branch_warehouse.create_user
     *
     * @mbggenerated
     */
    private String createUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dsp_branch_warehouse.modify_user
     *
     * @mbggenerated
     */
    private String modifyUser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table dsp_branch_warehouse
     *
     * @mbggenerated
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsp_branch_warehouse.id
     *
     * @return the value of dsp_branch_warehouse.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsp_branch_warehouse.id
     *
     * @param id the value for dsp_branch_warehouse.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsp_branch_warehouse.area_id
     *
     * @return the value of dsp_branch_warehouse.area_id
     *
     * @mbggenerated
     */
    public Integer getAreaId() {
        return areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsp_branch_warehouse.area_id
     *
     * @param areaId the value for dsp_branch_warehouse.area_id
     *
     * @mbggenerated
     */
    public void setAreaId(Integer areaId) {
        this.areaId = areaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsp_branch_warehouse.area_name
     *
     * @return the value of dsp_branch_warehouse.area_name
     *
     * @mbggenerated
     */
    public String getAreaName() {
        return areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsp_branch_warehouse.area_name
     *
     * @param areaName the value for dsp_branch_warehouse.area_name
     *
     * @mbggenerated
     */
    public void setAreaName(String areaName) {
        this.areaName = areaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsp_branch_warehouse.rule_id
     *
     * @return the value of dsp_branch_warehouse.rule_id
     *
     * @mbggenerated
     */
    public String getRuleId() {
        return ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsp_branch_warehouse.rule_id
     *
     * @param ruleId the value for dsp_branch_warehouse.rule_id
     *
     * @mbggenerated
     */
    public void setRuleId(String ruleId) {
        this.ruleId = ruleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsp_branch_warehouse.rule_name
     *
     * @return the value of dsp_branch_warehouse.rule_name
     *
     * @mbggenerated
     */
    public String getRuleName() {
        return ruleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsp_branch_warehouse.rule_name
     *
     * @param ruleName the value for dsp_branch_warehouse.rule_name
     *
     * @mbggenerated
     */
    public void setRuleName(String ruleName) {
        this.ruleName = ruleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsp_branch_warehouse.rule_rank
     *
     * @return the value of dsp_branch_warehouse.rule_rank
     *
     * @mbggenerated
     */
    public Integer getRuleRank() {
        return ruleRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsp_branch_warehouse.rule_rank
     *
     * @param ruleRank the value for dsp_branch_warehouse.rule_rank
     *
     * @mbggenerated
     */
    public void setRuleRank(Integer ruleRank) {
        this.ruleRank = ruleRank;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsp_branch_warehouse.create_date
     *
     * @return the value of dsp_branch_warehouse.create_date
     *
     * @mbggenerated
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsp_branch_warehouse.create_date
     *
     * @param createDate the value for dsp_branch_warehouse.create_date
     *
     * @mbggenerated
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsp_branch_warehouse.modify_date
     *
     * @return the value of dsp_branch_warehouse.modify_date
     *
     * @mbggenerated
     */
    public Date getModifyDate() {
        return modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsp_branch_warehouse.modify_date
     *
     * @param modifyDate the value for dsp_branch_warehouse.modify_date
     *
     * @mbggenerated
     */
    public void setModifyDate(Date modifyDate) {
        this.modifyDate = modifyDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsp_branch_warehouse.create_user
     *
     * @return the value of dsp_branch_warehouse.create_user
     *
     * @mbggenerated
     */
    public String getCreateUser() {
        return createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsp_branch_warehouse.create_user
     *
     * @param createUser the value for dsp_branch_warehouse.create_user
     *
     * @mbggenerated
     */
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dsp_branch_warehouse.modify_user
     *
     * @return the value of dsp_branch_warehouse.modify_user
     *
     * @mbggenerated
     */
    public String getModifyUser() {
        return modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dsp_branch_warehouse.modify_user
     *
     * @param modifyUser the value for dsp_branch_warehouse.modify_user
     *
     * @mbggenerated
     */
    public void setModifyUser(String modifyUser) {
        this.modifyUser = modifyUser;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dsp_branch_warehouse
     *
     * @mbggenerated
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", areaId=").append(areaId);
        sb.append(", areaName=").append(areaName);
        sb.append(", ruleId=").append(ruleId);
        sb.append(", ruleName=").append(ruleName);
        sb.append(", ruleRank=").append(ruleRank);
        sb.append(", createDate=").append(createDate);
        sb.append(", modifyDate=").append(modifyDate);
        sb.append(", createUser=").append(createUser);
        sb.append(", modifyUser=").append(modifyUser);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}